services:
  avr-5.4.0:
    platform: linux/amd64
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.bookworm
      args:
        USR: ${USR}
        UID: ${UID}
        GID: ${GID}
        DST: ${DST}
    user: ${UID}:${GID}
    image: avr-5.4.0:1.0
    hostname: avr5.4.0
    container_name: avr-5.4.0
    volumes:
      - ${DST}:/home/${USR}/dst/
  avr-12.4.0:
    platform: linux/amd64
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.trixie
      args:
        USR: ${USR}
        UID: ${UID}
        GID: ${GID}
        DST: ${DST}
    user: ${UID}:${GID}
    image: avr-12.4.0:1.0
    hostname: avr12.4.0
    container_name: avr-12.4.0
    volumes:
      - ${DST}:/home/${USR}/dst/
