version: '3.9'

services:
  dev_env:
    build:
      context: .
      args:
        USR: ${USR}
        UID: ${UID}
        GID: ${GID}
        DST: ${DST}
    user: ${UID}:${GID}
    image: avr_bld_env:1.0
    hostname: avr_bld_env
    container_name: avr_bld_env
    volumes:
      - ${DST}:/home/${USR}/dst/
