name: AVR cross build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      RELEASE: 1
    steps:
    - name: Install deps
      run: |
        sudo apt-get update
        sudo apt-get -y install avr-libc binutils-avr gcc-avr
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: build bootloader
      run: make
